name: FreeRTOS-Release-Packager

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID'
        required: true
        default: 'HEAD'
      version_number:
        description: 'Version Number (Ex. 10.4.0)'
        required: true
        default: '10.4.0'             

jobs:
  release-packager:
    name: Release Packager
    runs-on: ubuntu-latest
    steps:
      # Install python 3
      - name: Tool Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture:   x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout FreeRTOS Release Tools
        uses: actions/checkout@v2
        with:
          repository: FreeRTOS/FreeRTOS
          ref:  master
          path: tools

      - name: Release
        run: |
          cd tools/.github/scripts
          release.py --kernel-commit=${{ github.event.inputs.commit_id }} --new-kernel-version=${{ github.event.inputs.version_number }}
          exit $?
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
