name: FreeRTOS-Release-Packager

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID'
        required: true
        default: 'HEAD'
      version_number:
        description: 'Version Number (Ex. 10.4.0)'
        required: true
        default: '10.4.0'             

jobs:
  release-packager:
    name: Release Packager
    runs-on: ubuntu-latest
    steps:
      # Install python 3
      - name: Tool Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture:   x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout FreeRTOS Release Tools
        uses: actions/checkout@v2
        with:
          repository: dachalco/FreeRTOS # TODO: This is only for my debugging. Before merging upstream this should be updated
          ref:  autorelease/enhancements
          path: tools
          token: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Test
        uses: actions/checkout@v2
        with: 
          path: test

      - run: |
          # Configure repo for push
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          
          echo hello >> test/test-push.txt
          git -C test add test-push.txt
          git -C test commit -m "test push"
          git -C test push
        

      - name: Release
        run: |
          git config user.name 
          
          # Run the release script
          cd tools/.github/scripts
          echo "test push - ${{ github.actor }}" >> release-requirements.txt
          git add release-requirements.txt
          git commit -m "test push"
          git push
          
          #pip install -r release-requirements.txt
          #./release.py dachalco --kernel-commit=${{ github.event.inputs.commit_id }} --new-kernel-version=${{ github.event.inputs.version_number }} --use-git-ssh
          #exit $?
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
